#!/bin/bash
# 
UPDATES=$(checkupdates | wc -l)
[[ "${UPDATES}" > "0" ]] && echo " ${UPDATES}"
 
# echo "   ${UPDATES} "

# this is terrible
kill -9 $(pidof faked) &> /dev/null
# pkill -P -9 $$ 

exit 0
