#!/bin/sh
case "$1" in
    1) exec "$TERMINAL" --class "blocks" -e pulsemixer ;;
    2) pamixer -t; kill -36 $(pidof dwmblocks) ;;
    4) pamixer --allow-boost -i 1; kill -36 $(pidof dwmblocks) ;;
    5) pamixer --allow-boost -d 1; kill -36 $(pidof dwmblocks) ;;
esac
