#!/bin/sh

vol="$(pamixer --get-volume)"

# make sure we get a value
while [[ ! "$vol" =~ ^[0-9]+$ ]]
do 
  vol="$(pamixer --get-volume)"
done

case 1 in
	$((vol >= 70)) ) icon="墳" ;;
	$((vol >= 30)) ) icon="奔" ;;
	$((vol >= 1)) ) icon="" ;;
	* ) echo 婢 && exit ;;
esac

[ $(pamixer --get-mute) = true ] && echo "婢" && exit

echo "$icon"
